version: '3.8'

services:
  backend:
    build: .
    command: python /app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
      - ./task_list:/app/task_list
      - ./db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"

  frontend:
    image: node:14
    working_dir: /app/frontend
    command: npm start
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true